library(cranvas)
library(tourr)
require(ggplot2)

flea <- rescaler(flea)
qflea <- qdata(flea)
flea_tour <- Tourr$new(qflea, grand_tour(3), 1:6)
flea_tour$step()
print(qparallel(c("tour_1", "tour_2", "tour_3"), qflea))
print(qscatter(qflea, tour_1, tour_2, labeled=TRUE, datalims=c(-4,4,-4,4)))
print(qhist("tour_1", qflea, xlims=c(-4,4)))
flea_tour$start()
flea_tour$pause()
