##' Create a tour associated with a mutaframe
##'
##' The \pkg{tourr} package is used to create the tour projections.
##' This function creates an \R object to manipulate the tour, and all
##' the changes in the tour can be reflected immediately in plots
##' created in \pkg{cranvas}.
##'
##' Because the data provided to the tour is a mutaframe, it can
##' listen to changes through listeners on it. Usually these listeners
##' can update the plots which are created from this mutaframe
##' (further, those linked to this mutaframe) on the fly.
##'
##' Four basic methods can be applied to the object returned by this
##' function (say, \code{tour}):
##'
##' \describe{ \item{\code{tour$start()}}{starts the tour (tour
##' projections change successively and are attached to the mutaframe;
##' column names are \code{tour_1}, \code{tour_2}, ...)}
##' \item{\code{tour$stop()}}{pauses the tour}
##' \item{\code{tour$slower()}}{makes the tour slower}
##' \item{\code{tour$faster()}}{makes it faster.} }
##'
##' We can also modify the parameters passed to \code{\link{qtour}()}
##' on the fly through this object. For example, we can change the
##' type of tour to the guided tour using a syntax like
##' \code{tour$tour_path <- guided_tour(...)}. All other parameters
##' can be changed similarly, including \code{vars}, \code{aps},
##' \code{fps}, \code{rescale} and \code{sphere}.
##' @param vars variable names to be used in the tour (parsed by
##' \code{\link{var_names}})
##' @inheritParams qbar
##' @inheritParams tourr::animate
##' @return An object generated by reference classes with signals.
##' @author Yihui Xie <\url{http://yihui.name}>
##' @export
##' @example inst/examples/qtour-ex.R
qtour =
    function(vars = ~., data = last_data(), tour_path = grand_tour(), aps = 1, fps = 30,
             rescale = TRUE, sphere = FALSE, ...) {
        data = check_data(data)
        meta =
            Tour.meta$new(vars = var_names(vars, data), aps = aps, fps = fps,
                           rescale = rescale, sphere = sphere, tour_path = tour_path)
        src = last_time = tour = timer = NULL

        tour_init = function() {
            src <<- vapply(as.data.frame(data[, meta$vars]), as.numeric,
                           numeric(nrow(data)))
            if (meta$rescale)
                src <<- tourr::rescale(src)
            if (meta$sphere)
                src <<- tourr::sphere(src)
            tour <<- new_tour(src, meta$tour_path, NULL)
            timer$interval = 1000 / meta$fps
        }
        tour_step = function() {
            if (is.null(last_time)) {
                last_time <<- proc.time()[3]
                delta = 0
            } else {
                cur_time = proc.time()[3]
                delta = (cur_time - last_time)
                last_time <<- cur_time
            }
            step = tour(meta$aps * delta)
            if (is.null(step$proj)) {
                meta$pause()
                return()
            }
            data_proj = src %*% step$proj
            data_proj = scale(data_proj, center = TRUE, scale = FALSE)
            colnames(data_proj) = paste("proj", 1:ncol(data_proj), sep = "")
            for(col in colnames(data_proj)) {
                data[[col]] = data_proj[, col]
            }
            invisible(step)
        }
        timer = qtimer(1000, tour_step)
        tour_init()
        meta$pause = function() {
            timer$stop()
        }
        meta$start = function() {
            timer$start()
        }
        meta$slower = function() {
            meta$aps = meta$aps * 0.9
        }
        meta$faster = function() {
            meta$aps = meta$aps * 1.1
        }
        meta$changed$connect(tour_init)  # if anything changes, re-initialize the tour
        meta
    }

Tour.meta =
    setRefClass("Tourr_meta", fields =
                properties(list(vars = 'character',
                                tour_path = 'tour_path',
                                aps = 'numeric', fps = 'numeric',
                                rescale = 'logical', sphere = 'logical',
                                start = 'function', stop = 'function',
                                slower = 'function', faster = 'function')),
                contains = "PropertySet")

